name: NuGet Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'JGP.Members.Api.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          5.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Pack Core project
      run: dotnet pack **/*JGP.Members.Core.csproj --configuration $BUILD_CONFIG --include-symbols -p:SymbolPackageFormat=snupkg -o .

    - name: Pack Models project
      run: dotnet pack **/*JGP.Members.Web.Models.csproj --configuration $BUILD_CONFIG --include-symbols -p:SymbolPackageFormat=snupkg -o .

    - name: Pack Proxy project
      run: dotnet pack **/*JGP.Members.Web.Proxy.csproj --configuration $BUILD_CONFIG --include-symbols -p:SymbolPackageFormat=snupkg -o .

    - name: Publish package to NuGet
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/gwynnPalmer/index.json --api-key ${{secrets.PACKAGE_API_TOKEN}} --skip-duplicate